# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pic_url', models.CharField(max_length=255)),
                ('pic_type', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('tags', models.TextField(max_length=2000)),
                ('comments', models.TextField(max_length=2000)),
                ('create_time', models.DateTimeField(verbose_name='date created')),
                ('facepp_info', models.TextField(max_length=1000)),
                ('image_local_path', models.CharField(max_length=200)),
            ],
        ),
    ]
